baseURL = "http://gabrielamathieu.info/"
languageCode = "en-us"
title = "Gabriela Mathieu"
description = "Data Analyst | R Instructor"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Gabriela Mathieu"
    description = "Data Analyst | R Instructor"
    logo = "favicon/logo.png"
    twitterAuthor = "@calcita3"
    githubUsername = "calcita"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "python", "latex", "markdown"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:gabrielamathieu@gmx.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/calcita"
    name = "fab fa-github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/mathieugabriela/"
    name = "fab fa-linkedin"
    weight = 5

[[menu.icon]]
    url = "https://www.gitlab.com/calcita"
    name = "fab fa-gitlab"
    weight = 3
    
[[menu.icon]]
    url = "https://calcita.github.io/R-tutorial/"
    name = "fab fa-r-project"
    weight = 4

[[menu.icon]]
    url = "https://twitter.com/calcita3/"
    name = "fab fa-twitter"
    weight = 6

