baseurl = "gabrielamathieu.tk/"
languageCode = "en-us"
title = "Gabriela Mathieu"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/calcita"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/calcita3"

[params]
    description = "Gabriela Mathieu"

  GithubID = "calcita"
  TwitterID = "calcita3"
  LinkedInID = "mathieugabriela"
  Name = "Gabriela Mathieu"
  Email = "gmathieu@gmx.com"
  About = "I am looking for a job in Germany or remote. I do statistical analysis with R. I am passionate about R and free culture. My work experience consists of: Statistics analysis about economy and social information with a geospatial an approach, statistics Teaching assistant and R software teaching instructor. I am from Uruguay and now I am in Berlin. I like sports, photography and travel. "
  ProfilePicture = "images/logo.jpg"
  SlackURL = "https://r-users.slack.com/"
    
 # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
   MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.logo]
url = "logo.jpg"
width = 50
height = 50
alt = "Logo"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
