baseURL = "https://gabrielamathieu.netlify.app/"
languageCode = "en-us"
title = "Gabriela Mathieu"
description = "Data analyst | Teacher"
theme = "hugo-developer-portfolio"
disqusShortname = ""
googleAnalytics = ""
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]


# Remove this when using normally
# themesDir = "../../" 
# `
#[module]
 # [[module.imports]]
  #  path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=3

  [[menu.main]]
  name = "Services"
  URL = "services"
  weight=4
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=5


[params]
home = "Home"
# Meta data
description = "Data analyst and teacher"
author = "Gabriela Mathieu"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "gabrielamathieu@gmx.com"
  address = "Montevideo, Uruguay"
  googlemaps = ""

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4


