---
title: 'About me '
author: ''
date: '2017-09-15'
slug: me
categories: []
tags: []
---

I have 10+ years of **R programming** experience: data analysis and visualization, statistical analysis and also teaching.

My **work** experience includes: Statistical analysis of economy and social information with a geospatial approach, Teaching Assistant in Statistics and R software Teaching Instructor. I am from Uruguay and I am living in Montevideo. 

I am currently completing the Diploma in Gender and Politics of Equality of [Flacso](http://flacso.edu.uy/), to specialize in the analysis of data with a gender perspective.

I am interested in sports, photography and travelling. I conjugated my love for R and travel on my [travel blog](//mapamundi.me/) made completely in R. I am passionate about R and free culture.
 

---

## Experience

### Statistical analysis
*Ministerio de Desarrollo Social - Montevideo, Uruguay* since 2005

Statistics analysis about economy and social information with a geospatial approach using R and LaTeX.

### Teaching Assistant
*Universidad de la República (Uruguay) - Montevideo, Uruguay* 2009-2015

Statistics Teaching assistant at Mathematical Methods Department. 

### R software Teaching Instructor
*Universidad de la República (Uruguay) - Montevideo, Uruguay*
2010-2014


[Spanish CV](CV_GabrielaMathieu.pdf)
